### ISSUE TITLE
Link to microsite?

### ISSUE THREAD

**Issue by ff6347** [josues/time-deconstruction#1]
Looks very good already your repo. Can you add the link to the microsite to the README?

**Comment by josues** [comment]
Actually it is already added. Its right befor the mock-ups, after the last algorithm-result. Or what do you mean?

**Comment by ff6347** [comment]
Oh. Sorry it was such a huge link I didn't see it. :)

**Comment by josues** [comment]
Haha do you think I should make it smaller again, the sizes purpose was to make it obvious not to hide it..

**Comment by ff6347** [comment]
I think some of your headlines are pretty huge. :) rule of thumb. Only use one h1

**Comment by ff6347** [comment]
Hm. You are using h2 and h3. Maybe to many of it. Let's talk about this tomorrow.
